README.md

Fixed a spell bug

---

README.md

In addition, I'm the author of "Universal Domain Adaptation", it is a new DA setting.

Add distance-based papers

---

README.md

Title: Unsupervised Domain Adaptation Based on Source-guided Discrepancy
It is about the theory of a discrepancy for unsupervised domain adaptation.

Add a paper from AAAI2019

---

README.md

- add paper link (https://arxiv.org/abs/2003.07325) to Multi-Source DA
- add link of [Dassl.pytorch](https://github.com/KaiyangZhou/Dassl.pytorch) to Library

Add Dassl.pytorch

---

README.md

Paper is accepted by IJCAI2020, and add the code link

Paper is accepted by IJCAI2020 with the code link

---

README.md

Hi, thanks for maintaining this awesome list! I just wanted to add our recent work on understanding the generalized label shift as well as an algorithm for that. Hope this helps!

add recent paper on generalized label shift

---

README.md

Hi, thank you for maintaining this awesome repository. Our paper on the list has been accepted to ICML 2020 and the code is available now, so let me send this PR to update the information.

Paper accepted at ICML2020 (with code)

---

README.md

add a paper and code link

---

README.md

Hi, thanks for maintaining such an awesome repository. I would like to add an ECCV 2020 paper about DA. Thanks in advance!

Adding an ECCV2020 paper with code

---

README.md

Hi, thank you for maintaining this awesome repository. Our paper on domain adaptation has been accepted by ECCV2020 so I want to add it to the list. Thanks in advance!

Add an ECCV2020 paper with code.

---

README.md

Adding our recent survey paper on Unsupervised DA in vision

---

README.md

Add a paper to appear in BMVC2020

Add BMVC2020 paper

---

README.md

Added new DA setting, continuously indexed DA, along with a new ICML paper, code, etc.
Essentially continuously indexed DA asks the question of whether and how to go beyond current (categorical) domain adaptation regime and proposes the first approach to adapt across continuously indexed domains. For example, instead of adapting from domain A to domain B, we would like to simultaneously adapt across infintely many domains in a manifold. This allows us to go beyond domain adaption and perform both domain interpolation and domain extrapolation.

Added new DA setting, continuously indexed DA, along with a new ICML paper, code, etc.

---

README.md

I have added our TIP2020 paper along with its source code link.

Add a TIP paper on domain adaptation for semantic segmentation

---

README.md

Update our recent papers on DA.

update our recent papers

---

README.md

Added the paper "Select, Label, and Mix: Learning Discriminative Invariant Feature Representations for Partial Domain Adaptation".

Added SLM Paper on Partial Domain Adaptation.

---

README.md

Add one paper accepted by CVPR2021.

Add a CVPR2021 paper

---

README.md

Could you please add our recently published TIP work with the source code available?

add a TIP paper about image-based localization

---

README.md

Adding a new paper for semantic segmentation DA

---

README.md

Added following two papers (one conference, one Journal) on Unsupervised Domain Adaptation in your awesome repo:
https://link.springer.com/chapter/10.1007/978-3-030-58539-6_25 (ECCV 2020 Spotlight)
Title : Unsupervised Domain Adaptation for Semantic Segmentation of NIR Images through Generative Latent Search
Code: https://github.com/ambekarsameer96/GLSS
https://ieeexplore.ieee.org/document/9139471 (IEEE TMI 2020)
Title: Target-Independent Domain Adaptation for WBC Classification using Generative Latent Search
Code: https://github.com/prinshul/WBC-Classification-UDA
The above methods are unique in their design - they use test-time optimisation.
Both are added in <Other Methods> of UDA section.
Thank you.

Request to add two papers

---

README.md

Seeking Similarities over Differences: Similarity-based Domain Alignment for Adaptive Object Detection

Add a UDA paper for object detection (accepted in ICCV2021)

---

README.md

Added a paper on video domain adaptation

---

README.md

Add a new ICCV 2021 paper about the Universal Domain Adaptation

Add a new ICCV 2021 paper about the Universal Domain Adaptation

---

README.md

Add code link https://github.com/layumi/AdaBoost_Seg

Add code link

---

README.md

Adding SEE: See Eye to Eye: A Lidar-Agnostic 3D Detection Framework for Unsupervised Multi-Target Domain Adaptation

Adding SEE method

---

README.md

The Balancing Principle for Parameter Choice in Distance-Regularized Domain Adaptation [[NeurIPS2021]](https://proceedings.neurips.cc/paper/2021/hash/ae0909a324fb2530e205e52d40266418-Abstract.html) [[Pytorch]](https://github.com/xpitfire/bpda)

Added model selection method

---

README.md

On a Regularization of Unsupervised Domain Adaptation in RKHS [[ACHA2021]](https://www.sciencedirect.com/science/article/abs/pii/S1063520321001032?via%3Dihub)

Added theory journal for UDA

---

README.md

https://link.springer.com/article/10.1007/s10845-019-01499-4

Added journal for domain generalization regression

---

README.md

The paper is just accepted. I move it from arXiv to TIP. Many Thanks.

Move arXiv to TIP

---

README.md

Add three papers on domain generalization in person re-identification, domain generalization in semantic segmentation, open compound domain adaptation in semantic segmentation

Add three papers

---

README.md

Add two SSDA papers

---

README.md

- Corrected bullet points spacing
- Added new WACV paper on _CoNMix for Source-free Single and Multi-target Domain Adaptation [[WACV2022]](https://openaccess.thecvf.com/content/WACV2023/html/Kumar_CoNMix_for_Source-Free_Single_and_Multi-Target_Domain_Adaptation_WACV_2023_paper.html) [[Pytorch]](https://github.com/vcl-iisc/CoNMix)_
(Would be great if you can squash and merge)

Corrected the formatting and added new paper 

---

README.md

Thank you for your work. Here's a brief description of our tool.
[**JoliGEN**](https://github.com/jolibrain/joliGEN) is an integrated framework for training custom generative AI image-to-image models
Main Features:
- JoliGEN implements both **GAN and Diffusion models** for unpaired and paired image to image translation tasks, including domain and style adaptation with conservation of semantics such as image and object classes, masks, ...
- JoliGEN generative AI capabilities are targeted at real world applications such as **Controled Image Generation**, **Augmented Reality**, **Dataset Smart Augmentation** and object insertion, **Synthetic to Real** transforms.
All features:
- SoTA image to image translation
- Semantic consistency: conservation of labels of many types: bounding boxes, …

add joliGEN to Library list

---

README.md

[ICCV'23] PromptStyler: Prompt-driven Style Generation for Source-free Domain Generalization

Add ICCV2023 Paper (PromptStyler)

---

README.md

Add four UDA / ADA papers in recent conferences

Add four papers

---

README.md

Thank you for this awesome collection. I kindly add our SALUDA paper, which has been accepted to 3DV 2024 to the LiDAR section.

Add SALUDA paper to LiDAR section

---

README.md

Added a survey paper titled "Survey on Unsupervised Domain Adaptation for Semantic Segmentation for Visual Perception in Automated Driving" published in IEEE Access in May 2023

Added IEEE Access Survey

---

README.md

Add a new domain generalization paper accepted by CVPR 2024

Add a new domain generalization paper accepted by CVPR 2024

---

README.md

add two papers, one is in AAAI 2020, one is in cognition computation.

add two published multi-source papers

---

.idea/.gitignore
.idea/awesome-domain-adaptation.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
README.md

Please add our paper "Improving Object Detection via Local-Global Contrastive Learning", BMVC, 2024

Add our paper

---

README.md

I added 1 paper to the semantic segmentation section

Add MIC to Semantic Segmentation
